### ISSUE TITLE
More source unit tests

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#129]
After #110 we have unit tests covering a fairly large number of cases for source configurations, but its missing some things:

1. The docker image source with cmd supports mounting another source spec in.
2. The Build source only tests inline dockerfiles
  i. We can even drop the `inline` field after #98 
  ii. Probably we have this test too tightly coupled with the actual dockerfile format (its using dockerfile2llb to convert a literal dockerfile to llb). Even though the source type is for building a dockerfile, that implementation is outside the scope of what we are testing and we can probably just stub out the implementation and make sure that the correct function to forward the request to buildkit is being called.

**Comment by adamperlin** [comment]
I am going to add basic unit tests for source spec mounting for docker image with cmd in #117
