### ISSUE TITLE
[REQ] [DOCS] Documentation for Dalec Artifact Types

### ISSUE THREAD

**Issue by adamperlin** [Azure/dalec#270]
### What kind of request is this?

None

### What is your request or suggestion?

We now have several new artifact types in Dalec including config files, doc files, license files, and systemd units -- in addition to the original binaries and manpages artifact types. It would be good to update our documentation to include some examples of how to use artifacts in Dalec. There are several things about the artifact model that I think would be particularly good to clarify, i.e., that we support sub-paths, renaming artifact files, and globs (`*`).

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by cpuguy83** [comment]
This was completed in #377
