### ISSUE TITLE
[REQ] add option to skip signing

### ISSUE THREAD

**Issue by DannyBrito** [Azure/dalec#282]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

When we specify the signing block for a target in a `dalec` spec, it defaults to calling the signer. This can be inconvenient when attempting to test builds in a local environment, especially when we are not aiming to test signing.

It would be beneficial to have a `build-arg` or an equivalent flag/option to bypass the signing call.

Maybe, we might want to consider moving the signing block to a `build-arg` or flag. From my perspective, having the dalec spec and the signing block together makes it harder to share the specs directly. We would need to inform the recipient that they need to adjust the signing block to use their own signer image or to remove it. Alternatively, we would need to modify the spec and delete the signing block before sharing it.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by cpuguy83** [comment]
I think it would be fine to support a build-arg like `DALEC_SKIP_SIGNING=1`

**Comment by cpuguy83** [comment]
I could also see supporting reading the signing spec from a named context.

**Comment by pmengelbert** [comment]
- [ ] https://github.com/Azure/dalec/pull/320#discussion_r1674671889 Throw warning when signing is disabled
