### ISSUE TITLE
[REQ] Add option to disable frontend forwarding

### ISSUE THREAD

**Issue by pmengelbert** [Azure/dalec#296]
### What kind of request is this?

New feature

### What is your request or suggestion?

In some environments, it is undesireable to allow any kind of forwarding of the build for security reasons. We should expose some way for the user to disable forwarding, and introduce tests that guarantee any attempted forwarding will fail.

### Are you willing to submit PRs to contribute to this feature request?

- [X] Yes, I am willing to implement it.

**Comment by cpuguy83** [comment]
I think in this case the caller would need to validate/reject the spec ahead of time.
I don't think there's really an option we could/should do here to reject these within dalec.
