### ISSUE TITLE
Multiplatform frontend and mariner toolchain

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#30]
We need to publish at least amd64 and arm64 images of both the frontend and the mariner toolchain.

**Comment by cpuguy83** [comment]
The frontend has a multiarch build (which we cross-compile in this repo), so now just the toolchain image is needed which can't really be cross-compiled (at least easily? Maybe if someone wants to look at that).

**Comment by adamperlin** [comment]
After looking into things a bit I don't think cross-compiling the toolchain is supported, per https://github.com/microsoft/CBL-Mariner/issues/4059#issuecomment-1690602682

**Comment by DannyBrito** [comment]
I believe this is no longer needed as removed mariner toolchain and the multiplatform frontend image should be available. https://github.com/Azure/dalec/pkgs/container/dalec%2Ffrontend/179549024?tag=latest
