### ISSUE TITLE
[REQ] add ubuntu targets to docs

### ISSUE THREAD

**Issue by sozercan** [Azure/dalec#436]
### What kind of request is this?

Other

### What is your request or suggestion?

document ubuntu targets such as `jammy`

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by cpuguy83** [comment]
I think this is done now, assuming you mean the list of targets in the "Targets" doc?

**Comment by sozercan** [comment]
@cpuguy83 looks like we need in more places such as readme, and the intro page

>📦 Build packages and/or containers for [Azure Linux](https://github.com/microsoft/azurelinux) 2 and 3 (formerly known as CBL-Mariner)

**Comment by cpuguy83** [comment]
PTAL #468
