### ISSUE TITLE
Support SOURCE_DATE_EPOCH passthrough

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#54]
SOURCE_DATE_EPOCH is a standard variable used for setting the timestamps of artifacts to a deterministic value.
This is used for reproducible builds.

Buildkit has some built-in support for it, e.g. layers and image creation dates are set to it.
Package build tooling (e.g. rpmbuild) also often supports passing this through.

1. We need to allow the build-arg to pass through our validation.
2. We should also automatically inject this as an env var to the package build step.

**Comment by cpuguy83** [comment]
This is a good follow-up after https://github.com/Azure/dalec/pull/84 is merged.

**Comment by pmengelbert** [comment]
Also needs to be injected into the Command.Env field for DockerImage sources, as it's possible that the source may depend on SOURCE_DATE_EPOCH to be reproducible.
