### ISSUE TITLE
Paths in shells are often not correctly quoted

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#63]
As an example: https://github.com/Azure/dalec/blob/c24596c7ba764848e9042f667f812f72ddf07785/frontend/rpm/template.go#L221

These paths can have spaces in them and require quotes so the shell can interpret them correctly.

**Comment by DannyBrito** [comment]
@cpuguy83, was this issue specific to the `template.go` file?

**Comment by cpuguy83** [comment]
That's definitely one place, but quite possible not the only place.

**Comment by cpuguy83** [comment]
I'm going to close this for now.
There may still be other places where this is problematic, but it doesn't make sense to keep the issue open for that.
