### ISSUE TITLE
Mariner toolkit package resolution is (always) slow and sometimes flakey

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#83]
The toolkit is creating a DAG of packages it needs to download.
It does this in the chroot env it sets up.
We use pre-cached packages (which is cached in buildkit) so it doesn't need to download those packages itself as part of the all-in-one build step (where nothing gets cached until the step finishes).

On top of this process being very slow it can sometimes, for whatever reason, flake out. It will complain that it can't resolve the host and ignore our local package cache.

**Comment by cpuguy83** [comment]
One thing we could try:

The chroot for the mariner toolkit is packed up in a tar.gz which the toolkit unpacks just-in-time.
Based on the output from the toolkit, during package resolution it will see if the package is already installed in the chroot env.

We could unpack the chroot, install those package dependencies to the chroot, then repack it.
This way the chroot env will already have the packages installed when the toolkit is doing package resolution.
This would hopefully both speed up the build and de-flake it.

**Comment by cpuguy83** [comment]
@pmengelbert assigned to you in case this is something you want to dig into.

**Comment by cpuguy83** [comment]
Tried out https://github.com/Azure/dalec/issues/83#issuecomment-1910654730 to no avail.
The toolkit still wants to fetch packages from a repo.

**Comment by sozercan** [comment]
@cpuguy83 okay to close this now?

**Comment by cpuguy83** [comment]
Yep! Resolved in #115
