### ISSUE TITLE
feat: Code / Artifact Signing

### ISSUE THREAD

**Issue by pmengelbert** [Azure/dalec#88]
Make code / artifact signing possible via the spec. For example, windows artifacts can be signed. Also, output containers (i.e. `mariner2/container` ) can be signed. This feature would give dalec spec writers control over certain aspects of signing. A rough abstraction would be: 
- Provide the authority that will sign
- Provide the means by which signing will occur (cosign)
- Provide what will be signed
  - individual artifacts? binaries, tarballs, etc
  - `source`s and/or source tarballs produced for rpm builds?
  - output containers?

**Comment by cpuguy83** [comment]
This was completed in #214
